export type TrendingItem = {
  id: string;
  title: string;
  description: string;
  imageUrl?: string;
  category?: string;
  timestamp?: string;
  trendingScore?: number;
  tags?: string[];
  source?: string;
  artist?: string;
  creator?: string;
  platform?: string;
  shares?: number;
  readTime?: string;
  author?: string;
  album?: string;
  duration?: string;
  link?: string;
}; 